# See https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.(tsx\.snap|ambr)$'
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: misc
        args: ["--unsafe"]
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
    - id: ruff
      args: [ --fix ]
      exclude: 'harp/commandline/cookiecutters'
    - id: ruff-format
      exclude: 'harp/commandline/cookiecutters'
