"""messages summary from varchar to text

Revision ID: 4ab341a710f4
Revises: 0b4d9cb71c38
Create Date: 2024-09-06 09:56:42.404282

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ab341a710f4"
down_revision: Union[str, None] = "0b4d9cb71c38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "blobs", ["id"])
    op.alter_column(
        "messages", "summary", existing_type=sa.VARCHAR(length=255), type_=sa.Text(), existing_nullable=True
    )
    op.create_unique_constraint(None, "messages", ["id"])
    op.create_unique_constraint(None, "metrics", ["id"])
    op.drop_constraint("_tag_values_uc", "tag_values", type_="unique")
    op.create_unique_constraint("__values_uc", "tag_values", ["tag_id", "value"])
    op.create_unique_constraint(None, "tag_values", ["id"])
    op.create_unique_constraint(None, "tags", ["id"])
    op.create_unique_constraint(None, "trans_user_flags", ["id"])
    op.create_unique_constraint(None, "transactions", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "transactions", type_="unique")
    op.drop_constraint(None, "trans_user_flags", type_="unique")
    op.drop_constraint(None, "tags", type_="unique")
    op.drop_constraint(None, "tag_values", type_="unique")
    op.drop_constraint("__values_uc", "tag_values", type_="unique")
    op.create_unique_constraint("_tag_values_uc", "tag_values", ["tag_id", "value"])
    op.drop_constraint(None, "metrics", type_="unique")
    op.drop_constraint(None, "messages", type_="unique")
    op.alter_column(
        "messages", "summary", existing_type=sa.Text(), type_=sa.VARCHAR(length=255), existing_nullable=True
    )
    op.drop_constraint(None, "blobs", type_="unique")
    # ### end Alembic commands ###
