/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Message(type: str, content: Any, created_at: datetime.datetime = None)
 */
export interface Message {
  type: string
  content: unknown
  created_at?: string
  [k: string]: unknown
}
