/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transaction(id: str, started_at: datetime.datetime, finished_at: datetime.datetime, ellapsed: float)
 */
export interface Transaction {
  id: string
  started_at: string
  finished_at: string
  ellapsed: number
  [k: string]: unknown
}
