# Docker compose override for running harp-proxy as a container
# Usage: docker compose -f compose.yml -f compose.harp-docker.yml up
services:
  harp-proxy:
    image: makersquad/harp-proxy:${TAG:-latest}
    platform: ${PLATFORM:-linux/amd64}
    networks:
      - kitchen-sink
    ports:
      - "4000-4999:4000-4999"
    volumes:
      - ./etc:/etc/harp:ro
    command: ${COMMAND:-server -f /etc/harp/proxy.docker.yml -f /etc/harp/rules.yml}
    depends_on:
      - api1
      - api2
      - api3
      - api4
    environment:
      - HARP_LOG_LEVEL=DEBUG
