# Docker compose override for running harp-proxy as a container
# Usage: docker compose -f compose.yml -f compose.harp-docker.yml up
services:
  harp-proxy:
    image: makersquad/harp-proxy:${DOCKER_TAG:-latest}
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "4000-4999:4000-4999"
    volumes:
      - ./etc:/etc/harp:ro
    command: ${HARP_OPTIONS:-server -f /etc/harp/proxy.docker.yml -f /etc/harp/rules.yml}
    depends_on:
      - lb-httpbin-1
      - lb-httpbin-2
    environment:
      - HARP_LOG_LEVEL=DEBUG
